//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMedia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialMediaDBEntities : DbContext
    {
        public SocialMediaDBEntities()
            : base("name=SocialMediaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Blog> tb_Blog { get; set; }
        public virtual DbSet<tb_BlogGroup> tb_BlogGroup { get; set; }
        public virtual DbSet<tb_Comment> tb_Comment { get; set; }
        public virtual DbSet<tb_Favorite> tb_Favorite { get; set; }
        public virtual DbSet<tb_Group> tb_Group { get; set; }
        public virtual DbSet<tb_UserGroup> tb_UserGroup { get; set; }
        public virtual DbSet<tb_UserInfo> tb_UserInfo { get; set; }
    }
}
