//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMedia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Blog
    {
        public int Id { get; set; }
        public int Author { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
    
        public virtual tb_UserInfo tb_UserInfo { get; set; }
    }
}
