//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMedia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BlogGroup
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int BlogId { get; set; }
    
        public virtual tb_Blog tb_Blog { get; set; }
        public virtual tb_Group tb_Group { get; set; }
    }
}
