//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMedia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_UserInfo()
        {
            this.tb_Blog = new HashSet<tb_Blog>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Username { get; set; }
        public Nullable<int> Age { get; set; }
        public string Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Blog> tb_Blog { get; set; }
    }
}
